---
  - name: Install httpd
  hosts: all
  become: true
  tasks:
    - name: BlockInFile
      blockinfile:
        path: /root/facts.txt
        block: "Ansible managed node IP is {{ ansible_facts.default_ipv4.address }}"     
        create: true
    
    - name: Install httpd
      package:
        name: httpd
        state: latest
    
    - name: Copy file
      command: "cp /root/facts.txt /var/www/html/index.html"
    
    - name: Start httpd
      service:
        name: httpd
        state: started
...