---
- name: Sample Playbook - Executing "date" and "uptime" command
  hosts: worker
  tasks:
    - name: Run "date" command
      command: date
      register: dateoutput
      
    - debug: msg="{{ dateoutput.stdout_lines }}"
        
    - name: Run "uptime" command
      command: uptime
      register: uptimeoutput
    
    - debug: msg="{{ uptimeoutput.stdout_lines }}"
...